from djongo import models

from yadirect_api.models_base import BaseModel


class CallTouchResponse(models.Model):
    date = models.TextField()
    callUrl = models.TextField()
    uniqueCall = models.TextField()
    callReferenceId = models.TextField()
    utmContent = models.TextField()
    source = models.TextField()
    ref = models.TextField()
    additionalTags = models.TextField()
    hostname = models.TextField()
    waitingConnect = models.TextField()
    ctCallerId = models.TextField()
    keyword = models.TextField()
    callClientUniqueId = models.TextField()
    order = models.TextField()
    callTags = models.TextField()
    utmSource = models.TextField()
    sipCallId = models.TextField()
    ip = models.TextField()
    utmCampaign = models.TextField()
    attrs = models.TextField()
    phoneNumber = models.TextField()
    uniqTargetCall = models.TextField()
    utmMedium = models.TextField()
    orders = models.TextField()
    device = models.TextField()
    sessionDate = models.TextField()
    city = models.TextField()
    redirectNumber = models.TextField()
    siteName = models.TextField()
    yaClientId = models.TextField()
    medium = models.TextField()
    callphase = models.TextField()
    duration = models.TextField()
    browser = models.TextField()
    callbackCall = models.TextField()
    successful = models.TextField()
    timestamp = models.TextField()
    callId = models.TextField()
    clientId = models.TextField()
    callerNumber = models.TextField()
    os = models.TextField()
    manager = models.TextField()
    utmTerm = models.TextField()
    userAgent = models.TextField()
    sessionId = models.TextField()
    url = models.TextField()
    targetCall = models.TextField()
    attribution = models.TextField()
    siteId = models.TextField()
